# Generated by Django 2.2.7 on 2020-02-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='criminaldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('FathersName', models.CharField(max_length=255)),
                ('MothersName', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('DOB', models.CharField(max_length=255)),
                ('BloodGroup', models.CharField(max_length=255)),
                ('IdentificationMark', models.CharField(max_length=255)),
                ('Nationality', models.CharField(max_length=255)),
                ('Religion', models.CharField(max_length=255)),
                ('CrimesDone', models.CharField(max_length=255)),
            ],
        ),
    ]
