# Generated by Django 2.2.7 on 2020-02-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
