# Generated by Django 2.2.7 on 2020-02-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_auto_20200211_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='CrimName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
